-- ============================================================================
-- TOURMASTER AI - PostgreSQL Database Schema & Seed Data
-- Smart India Hackathon 2026 (Problem Statement 26204)
-- ============================================================================

CREATE TABLE IF NOT EXISTS tourist_spots (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    city VARCHAR(100) DEFAULT 'Pune',
    state VARCHAR(100) DEFAULT 'Maharashtra',
    category VARCHAR(100),
    description TEXT,
    lat NUMERIC(10, 6),
    lng NUMERIC(10, 6),
    timings VARCHAR(100),
    entry_fee NUMERIC(10, 2) DEFAULT 0,
    rating NUMERIC(3, 2) DEFAULT 4.5,
    reviews_count INT DEFAULT 0,
    eco_score INT DEFAULT 90,
    is_verified BOOLEAN DEFAULT TRUE,
    image_url TEXT,
    distance_from_pune VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS hotels (
    id VARCHAR(64) PRIMARY KEY,
    tourism_spot VARCHAR(255) NOT NULL,
    hotel_name VARCHAR(255) NOT NULL,
    distance_from_spot VARCHAR(50),
    distance_km NUMERIC(6, 2),
    rating NUMERIC(3, 2) DEFAULT 4.5,
    price_per_night NUMERIC(10, 2) NOT NULL,
    image_url TEXT
);

CREATE TABLE IF NOT EXISTS restaurants (
    id VARCHAR(64) PRIMARY KEY,
    tourism_spot VARCHAR(255) NOT NULL,
    restaurant_name VARCHAR(255) NOT NULL,
    distance_from_spot VARCHAR(50),
    distance_km NUMERIC(6, 2),
    cuisine VARCHAR(255),
    price_for_two NUMERIC(10, 2),
    rating NUMERIC(3, 2) DEFAULT 4.5,
    is_pure_veg BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS guides (
    id VARCHAR(64) PRIMARY KEY,
    tourism_spot VARCHAR(255) NOT NULL,
    guide_name VARCHAR(255) NOT NULL,
    approx_guide_price VARCHAR(50),
    price_inr NUMERIC(10, 2),
    rating NUMERIC(3, 2) DEFAULT 4.8,
    specialization VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS entertainments (
    id VARCHAR(64) PRIMARY KEY,
    tourism_spot VARCHAR(255) NOT NULL,
    entertainment_place VARCHAR(255) NOT NULL,
    distance_from_spot_km NUMERIC(6, 2),
    category VARCHAR(100),
    approx_entry_fee NUMERIC(10, 2),
    rating NUMERIC(3, 2)
);

CREATE TABLE IF NOT EXISTS taxi_routes (
    id VARCHAR(64) PRIMARY KEY,
    tourism_spot VARCHAR(255) NOT NULL,
    distance_from_pune VARCHAR(50),
    distance_km NUMERIC(6, 2),
    approx_taxi_fare VARCHAR(50),
    fare_amount NUMERIC(10, 2),
    best_travel_option TEXT
);

-- SEED DATA INSERTIONS
INSERT INTO tourist_spots (id, name, city, state, category, description, lat, lng, timings, entry_fee, rating, reviews_count, eco_score, is_verified, image_url, distance_from_pune) VALUES ('spot-shaniwar-wada', 'Shaniwar Wada', 'Pune', 'Maharashtra', 'Heritage & Culture', 'Shaniwar Wada in Maharashtra. Best known for: Maratha history, heritage.', 18.5196, 73.8553, '08:00 AM - 06:30 PM', 25, 4.6, 28519, 92, TRUE, '/images/spots/shaniwar-wada.jpg', '3 km') ON CONFLICT (id) DO UPDATE SET entry_fee = EXCLUDED.entry_fee, rating = EXCLUDED.rating;
INSERT INTO tourist_spots (id, name, city, state, category, description, lat, lng, timings, entry_fee, rating, reviews_count, eco_score, is_verified, image_url, distance_from_pune) VALUES ('spot-sinhagad-fort', 'Sinhagad Fort', 'Pune', 'Maharashtra', 'Adventure & Trekking', 'Sinhagad Fort in Maharashtra. Best known for: Fort, trekking, scenery.', 18.3663, 73.7558, '08:00 AM - 06:30 PM', 50, 4.8, 29760, 96, TRUE, '/images/spots/sinhagad-fort.jpg', '30 km') ON CONFLICT (id) DO UPDATE SET entry_fee = EXCLUDED.entry_fee, rating = EXCLUDED.rating;
INSERT INTO tourist_spots (id, name, city, state, category, description, lat, lng, timings, entry_fee, rating, reviews_count, eco_score, is_verified, image_url, distance_from_pune) VALUES ('spot-dagdusheth-halwai-ganpati', 'Dagdusheth Halwai Ganpati', 'Pune', 'Maharashtra', 'Spiritual & Wellness', 'Dagdusheth Halwai Ganpati in Maharashtra. Best known for: Famous temple.', 18.5165, 73.8561, '08:00 AM - 06:30 PM', 0, 4.9, 30380, 94, TRUE, '/images/spots/dagdusheth-halwai-ganpati.jpg', '3 km') ON CONFLICT (id) DO UPDATE SET entry_fee = EXCLUDED.entry_fee, rating = EXCLUDED.rating;
INSERT INTO tourist_spots (id, name, city, state, category, description, lat, lng, timings, entry_fee, rating, reviews_count, eco_score, is_verified, image_url, distance_from_pune) VALUES ('spot-aga-khan-palace', 'Aga Khan Palace', 'Pune', 'Maharashtra', 'Heritage & Culture', 'Aga Khan Palace in Maharashtra. Best known for: History, Gandhi memorial.', 18.5524, 73.9015, '08:00 AM - 06:30 PM', 25, 4.6, 28519, 94, TRUE, '/images/spots/aga-khan-palace.jpg', '6 km') ON CONFLICT (id) DO UPDATE SET entry_fee = EXCLUDED.entry_fee, rating = EXCLUDED.rating;
INSERT INTO tourist_spots (id, name, city, state, category, description, lat, lng, timings, entry_fee, rating, reviews_count, eco_score, is_verified, image_url, distance_from_pune) VALUES ('spot-khadakwasla-dam', 'Khadakwasla Dam', 'Pune', 'Maharashtra', 'Nature & Wildlife', 'Khadakwasla Dam in Maharashtra. Best known for: Lake, sunset, nature.', 18.4287, 73.7661, '08:00 AM - 06:30 PM', 0, 4.5, 27900, 91, TRUE, '/images/spots/khadakwasla-dam.jpg', '20 km') ON CONFLICT (id) DO UPDATE SET entry_fee = EXCLUDED.entry_fee, rating = EXCLUDED.rating;
INSERT INTO tourist_spots (id, name, city, state, category, description, lat, lng, timings, entry_fee, rating, reviews_count, eco_score, is_verified, image_url, distance_from_pune) VALUES ('spot-rajgad-fort', 'Rajgad Fort', 'Pune', 'Maharashtra', 'Adventure & Trekking', 'Rajgad Fort in Maharashtra. Best known for: Trekking, Maratha history.', 18.2582, 73.6828, '08:00 AM - 06:30 PM', 50, 4.8, 29760, 98, TRUE, '/images/spots/rajgad-fort.jpg', '60 km') ON CONFLICT (id) DO UPDATE SET entry_fee = EXCLUDED.entry_fee, rating = EXCLUDED.rating;
INSERT INTO tourist_spots (id, name, city, state, category, description, lat, lng, timings, entry_fee, rating, reviews_count, eco_score, is_verified, image_url, distance_from_pune) VALUES ('spot-torna-fort', 'Torna Fort', 'Pune', 'Maharashtra', 'Adventure & Trekking', 'Torna Fort in Maharashtra. Best known for: Trekking, historic fort.', 18.2772, 73.6231, '08:00 AM - 06:30 PM', 50, 4.7, 29140, 97, TRUE, '/images/spots/torna-fort.jpg', '65 km') ON CONFLICT (id) DO UPDATE SET entry_fee = EXCLUDED.entry_fee, rating = EXCLUDED.rating;
INSERT INTO tourist_spots (id, name, city, state, category, description, lat, lng, timings, entry_fee, rating, reviews_count, eco_score, is_verified, image_url, distance_from_pune) VALUES ('spot-mulshi-dam', 'Mulshi Dam', 'Pune', 'Maharashtra', 'Nature & Wildlife', 'Mulshi Dam in Maharashtra. Best known for: Mountains, lake, nature.', 18.5028, 73.4939, '08:00 AM - 06:30 PM', 0, 4.6, 28519, 95, TRUE, '/images/spots/mulshi-dam.jpg', '45 km') ON CONFLICT (id) DO UPDATE SET entry_fee = EXCLUDED.entry_fee, rating = EXCLUDED.rating;
INSERT INTO tourist_spots (id, name, city, state, category, description, lat, lng, timings, entry_fee, rating, reviews_count, eco_score, is_verified, image_url, distance_from_pune) VALUES ('spot-lonavala', 'Lonavala', 'Pune', 'Maharashtra', 'Nature & Wildlife', 'Lonavala in Maharashtra. Best known for: Hills, waterfalls, viewpoints.', 18.7557, 73.4091, '08:00 AM - 06:30 PM', 50, 4.7, 29140, 93, TRUE, '/images/spots/lonavala.jpg', '65 km') ON CONFLICT (id) DO UPDATE SET entry_fee = EXCLUDED.entry_fee, rating = EXCLUDED.rating;
INSERT INTO tourist_spots (id, name, city, state, category, description, lat, lng, timings, entry_fee, rating, reviews_count, eco_score, is_verified, image_url, distance_from_pune) VALUES ('spot-khandala', 'Khandala', 'Pune', 'Maharashtra', 'Nature & Wildlife', 'Khandala in Maharashtra. Best known for: Hill station, viewpoints.', 18.7617, 73.3768, '08:00 AM - 06:30 PM', 50, 4.6, 28519, 92, TRUE, '/images/spots/khandala.jpg', '70 km') ON CONFLICT (id) DO UPDATE SET entry_fee = EXCLUDED.entry_fee, rating = EXCLUDED.rating;
INSERT INTO tourist_spots (id, name, city, state, category, description, lat, lng, timings, entry_fee, rating, reviews_count, eco_score, is_verified, image_url, distance_from_pune) VALUES ('spot-lohagad-fort', 'Lohagad Fort', 'Pune', 'Maharashtra', 'Adventure & Trekking', 'Lohagad Fort in Maharashtra. Best known for: Trekking, fort.', 18.7058, 73.4794, '08:00 AM - 06:30 PM', 50, 4.7, 29140, 95, TRUE, '/images/spots/lohagad-fort.jpg', '65 km') ON CONFLICT (id) DO UPDATE SET entry_fee = EXCLUDED.entry_fee, rating = EXCLUDED.rating;
INSERT INTO tourist_spots (id, name, city, state, category, description, lat, lng, timings, entry_fee, rating, reviews_count, eco_score, is_verified, image_url, distance_from_pune) VALUES ('spot-panshet-dam', 'Panshet Dam', 'Pune', 'Maharashtra', 'Nature & Wildlife', 'Panshet Dam in Maharashtra. Best known for: Water activities, nature.', 18.3756, 73.5939, '08:00 AM - 06:30 PM', 30, 4.5, 27900, 94, TRUE, '/images/spots/panshet-dam.jpg', '50 km') ON CONFLICT (id) DO UPDATE SET entry_fee = EXCLUDED.entry_fee, rating = EXCLUDED.rating;
INSERT INTO tourist_spots (id, name, city, state, category, description, lat, lng, timings, entry_fee, rating, reviews_count, eco_score, is_verified, image_url, distance_from_pune) VALUES ('spot-visapur-fort', 'Visapur Fort', 'Pune', 'Maharashtra', 'Adventure & Trekking', 'Visapur Fort in Maharashtra. Best known for: Trekking, fort.', 18.7186, 73.4878, '08:00 AM - 06:30 PM', 50, 4.7, 29140, 95, TRUE, '/images/spots/visapur-fort.jpg', '65 km') ON CONFLICT (id) DO UPDATE SET entry_fee = EXCLUDED.entry_fee, rating = EXCLUDED.rating;
INSERT INTO tourist_spots (id, name, city, state, category, description, lat, lng, timings, entry_fee, rating, reviews_count, eco_score, is_verified, image_url, distance_from_pune) VALUES ('spot-rajmachi-fort', 'Rajmachi Fort', 'Pune', 'Maharashtra', 'Adventure & Trekking', 'Rajmachi Fort in Maharashtra. Best known for: Trekking, Sahyadri scenery.', 18.8286, 73.3986, '08:00 AM - 06:30 PM', 50, 4.8, 29760, 97, TRUE, '/images/spots/rajmachi-fort.jpg', '80 km') ON CONFLICT (id) DO UPDATE SET entry_fee = EXCLUDED.entry_fee, rating = EXCLUDED.rating;
INSERT INTO tourist_spots (id, name, city, state, category, description, lat, lng, timings, entry_fee, rating, reviews_count, eco_score, is_verified, image_url, distance_from_pune) VALUES ('spot-rajiv-gandhi-zoological-park', 'Rajiv Gandhi Zoological Park', 'Pune', 'Maharashtra', 'Nature & Wildlife', 'Rajiv Gandhi Zoological Park in Maharashtra. Best known for: Wildlife, family tourism.', 18.4552, 73.8617, '08:00 AM - 06:30 PM', 40, 4.4, 27280, 90, TRUE, '/images/spots/rajiv-gandhi-zoological-park.jpg', '8 km') ON CONFLICT (id) DO UPDATE SET entry_fee = EXCLUDED.entry_fee, rating = EXCLUDED.rating;
INSERT INTO tourist_spots (id, name, city, state, category, description, lat, lng, timings, entry_fee, rating, reviews_count, eco_score, is_verified, image_url, distance_from_pune) VALUES ('spot-iskcon-nvcc-katraj', 'ISKCON NVCC, Katraj', 'Pune', 'Maharashtra', 'Spiritual & Wellness', 'ISKCON NVCC, Katraj in Maharashtra. Best known for: Krishna temple, spiritual tourism.', 18.4485, 73.8804, '08:00 AM - 06:30 PM', 0, 4.8, 29760, 93, TRUE, '/images/spots/iskcon-nvcc-katraj.jpg', '12 km') ON CONFLICT (id) DO UPDATE SET entry_fee = EXCLUDED.entry_fee, rating = EXCLUDED.rating;
INSERT INTO tourist_spots (id, name, city, state, category, description, lat, lng, timings, entry_fee, rating, reviews_count, eco_score, is_verified, image_url, distance_from_pune) VALUES ('spot-swaminarayan-temple-narhe', 'Swaminarayan Temple, Narhe', 'Pune', 'Maharashtra', 'Spiritual & Wellness', 'Swaminarayan Temple, Narhe in Maharashtra. Best known for: Hindu temple, architecture, spirituality.', 18.4467, 73.8189, '08:00 AM - 06:30 PM', 0, 4.7, 29140, 92, TRUE, '/images/spots/swaminarayan-temple-narhe.jpg', '15 km') ON CONFLICT (id) DO UPDATE SET entry_fee = EXCLUDED.entry_fee, rating = EXCLUDED.rating;
INSERT INTO tourist_spots (id, name, city, state, category, description, lat, lng, timings, entry_fee, rating, reviews_count, eco_score, is_verified, image_url, distance_from_pune) VALUES ('spot-parvati-hill-temple', 'Parvati Hill Temple', 'Pune', 'Maharashtra', 'Spiritual & Wellness', 'Parvati Hill Temple in Maharashtra. Best known for: Temple, city views, heritage.', 18.498, 73.8475, '08:00 AM - 06:30 PM', 0, 4.6, 28519, 92, TRUE, '/images/spots/parvati-hill-temple.jpg', '6 km') ON CONFLICT (id) DO UPDATE SET entry_fee = EXCLUDED.entry_fee, rating = EXCLUDED.rating;
INSERT INTO tourist_spots (id, name, city, state, category, description, lat, lng, timings, entry_fee, rating, reviews_count, eco_score, is_verified, image_url, distance_from_pune) VALUES ('spot-alandi', 'Alandi', 'Pune', 'Maharashtra', 'Spiritual & Wellness', 'Alandi in Maharashtra. Best known for: Sant Dnyaneshwar Samadhi, pilgrimage.', 18.6772, 73.8967, '08:00 AM - 06:30 PM', 0, 4.8, 29760, 91, TRUE, '/images/spots/alandi.jpg', '25 km') ON CONFLICT (id) DO UPDATE SET entry_fee = EXCLUDED.entry_fee, rating = EXCLUDED.rating;
INSERT INTO tourist_spots (id, name, city, state, category, description, lat, lng, timings, entry_fee, rating, reviews_count, eco_score, is_verified, image_url, distance_from_pune) VALUES ('spot-dehu', 'Dehu', 'Pune', 'Maharashtra', 'Spiritual & Wellness', 'Dehu in Maharashtra. Best known for: Sant Tukaram Maharaj, pilgrimage.', 18.7189, 73.7717, '08:00 AM - 06:30 PM', 0, 4.7, 29140, 90, TRUE, '/images/spots/dehu.jpg', '30 km') ON CONFLICT (id) DO UPDATE SET entry_fee = EXCLUDED.entry_fee, rating = EXCLUDED.rating;
INSERT INTO tourist_spots (id, name, city, state, category, description, lat, lng, timings, entry_fee, rating, reviews_count, eco_score, is_verified, image_url, distance_from_pune) VALUES ('spot-phoenix-mall-of-the-millennium', 'Phoenix Mall of the Millennium', 'Pune', 'Maharashtra', 'Eco-Tourism & Rural', 'Phoenix Mall of the Millennium in Maharashtra. Best known for: Shopping, food, entertainment.', 18.5986, 73.7667, '08:00 AM - 06:30 PM', 0, 4.7, 29140, 88, TRUE, '/images/spots/phoenix-mall-of-the-millennium.jpg', '15 km') ON CONFLICT (id) DO UPDATE SET entry_fee = EXCLUDED.entry_fee, rating = EXCLUDED.rating;
INSERT INTO tourist_spots (id, name, city, state, category, description, lat, lng, timings, entry_fee, rating, reviews_count, eco_score, is_verified, image_url, distance_from_pune) VALUES ('spot-phoenix-marketcity-pune', 'Phoenix Marketcity Pune', 'Pune', 'Maharashtra', 'Eco-Tourism & Rural', 'Phoenix Marketcity Pune in Maharashtra. Best known for: Shopping, luxury retail, dining.', 18.5622, 73.9167, '08:00 AM - 06:30 PM', 0, 4.7, 29140, 89, TRUE, 'https://images.unsplash.com/photo-1567449303078-57ad995bd301?auto=format&fit=crop&w=800&q=80', '8 km') ON CONFLICT (id) DO UPDATE SET entry_fee = EXCLUDED.entry_fee, rating = EXCLUDED.rating;
INSERT INTO tourist_spots (id, name, city, state, category, description, lat, lng, timings, entry_fee, rating, reviews_count, eco_score, is_verified, image_url, distance_from_pune) VALUES ('spot-amanora-mall', 'Amanora Mall', 'Pune', 'Maharashtra', 'Eco-Tourism & Rural', 'Amanora Mall in Maharashtra. Best known for: Lifestyle, entertainment, shopping.', 18.5194, 73.9317, '08:00 AM - 06:30 PM', 0, 4.6, 28519, 88, TRUE, 'https://images.unsplash.com/photo-1567449303078-57ad995bd301?auto=format&fit=crop&w=800&q=80', '10 km') ON CONFLICT (id) DO UPDATE SET entry_fee = EXCLUDED.entry_fee, rating = EXCLUDED.rating;
INSERT INTO tourist_spots (id, name, city, state, category, description, lat, lng, timings, entry_fee, rating, reviews_count, eco_score, is_verified, image_url, distance_from_pune) VALUES ('spot-seasons-mall', 'Seasons Mall', 'Pune', 'Maharashtra', 'Eco-Tourism & Rural', 'Seasons Mall in Maharashtra. Best known for: Cinema, food court, shopping.', 18.5186, 73.9333, '08:00 AM - 06:30 PM', 0, 4.6, 28519, 88, TRUE, 'https://images.unsplash.com/photo-1567449303078-57ad995bd301?auto=format&fit=crop&w=800&q=80', '10 km') ON CONFLICT (id) DO UPDATE SET entry_fee = EXCLUDED.entry_fee, rating = EXCLUDED.rating;
INSERT INTO tourist_spots (id, name, city, state, category, description, lat, lng, timings, entry_fee, rating, reviews_count, eco_score, is_verified, image_url, distance_from_pune) VALUES ('spot-imagicaa', 'Imagicaa', 'Pune', 'Maharashtra', 'Adventure & Trekking', 'Imagicaa in Maharashtra. Best known for: Theme park, rides, family entertainment.', 18.7492, 73.2844, '08:00 AM - 06:30 PM', 1499, 4.6, 28519, 88, TRUE, '/images/spots/imagicaa.jpg', '90 km') ON CONFLICT (id) DO UPDATE SET entry_fee = EXCLUDED.entry_fee, rating = EXCLUDED.rating;
INSERT INTO tourist_spots (id, name, city, state, category, description, lat, lng, timings, entry_fee, rating, reviews_count, eco_score, is_verified, image_url, distance_from_pune) VALUES ('spot-lal-mahal', 'Lal Mahal', 'Pune', 'Maharashtra', 'Heritage & Culture', 'Lal Mahal in Maharashtra. Best known for: Shivaji Maharaj history.', 18.5194, 73.8561, '08:00 AM - 06:30 PM', 10, 4.5, 27900, 91, TRUE, '/images/spots/lal-mahal.jpg', '3 km') ON CONFLICT (id) DO UPDATE SET entry_fee = EXCLUDED.entry_fee, rating = EXCLUDED.rating;
INSERT INTO tourist_spots (id, name, city, state, category, description, lat, lng, timings, entry_fee, rating, reviews_count, eco_score, is_verified, image_url, distance_from_pune) VALUES ('spot-pashan-lake', 'Pashan Lake', 'Pune', 'Maharashtra', 'Nature & Wildlife', 'Pashan Lake in Maharashtra. Best known for: Birdwatching, nature, walking.', 18.5367, 73.7844, '08:00 AM - 06:30 PM', 0, 4.4, 27280, 95, TRUE, '/images/spots/pashan-lake.jpg', '10 km') ON CONFLICT (id) DO UPDATE SET entry_fee = EXCLUDED.entry_fee, rating = EXCLUDED.rating;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-1', 'Shaniwar Wada', 'Shantai Hotel', '1.5 km', 1.5, 4.3, 1200, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-2', 'Shaniwar Wada', 'Pride Premier Pune', '2.0 km', 2.0, 4.4, 1800, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-3', 'Sinhagad Fort', 'Sorina Hillside Resort', '3.8 km', 3.8, 4.5, 2400, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-4', 'Sinhagad Fort', 'Wildernest Hilltop Resort', '5.9 km', 5.9, 4.6, 3200, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-5', 'Dagdusheth Halwai Ganpati', 'Poona Guest House', '0.1 km', 0.1, 4.7, 4500, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-6', 'Dagdusheth Halwai Ganpati', 'Shantai Hotel', '1.7 km', 1.7, 4.8, 5800, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-7', 'Aga Khan Palace', 'Hyatt Pune', '0.3 km', 0.3, 4.3, 2800, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-8', 'Aga Khan Palace', 'Magnus Nexstar Suites Kalyani Nagar', '0.4 km', 0.4, 4.4, 3500, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-9', 'Khadakwasla Dam', 'SPOT ON 75667 Hotel Peacock Garden Lodge', '1.6 km', 1.6, 4.5, 1200, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-10', 'Khadakwasla Dam', 'Wildernest Hilltop Resort', '2.5 km', 2.5, 4.6, 1800, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-11', 'Rajgad Fort', 'Rajgad Resort / nearby stays', '5 km', 5.0, 4.7, 2400, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-12', 'Rajgad Fort', 'Rajgad Valley Resort', '8 km', 8.0, 4.8, 3200, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-13', 'Torna Fort', 'Hilltop Heaven Resort', '3.1 km', 3.1, 4.3, 4500, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-14', 'Torna Fort', 'Cosmicstays Rajgad Vista Stay Play', '8.5 km', 8.5, 4.4, 5800, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-15', 'Mulshi Dam', 'Malhar Machi Mountain Resorts', '1.0 km', 1.0, 4.5, 2800, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-16', 'Mulshi Dam', 'Raanjan Hills Resort', '2.4 km', 2.4, 4.6, 3500, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-17', 'Lonavala', 'Radisson Resort & Spa Lonavala', '3 km', 3.0, 4.7, 1200, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-18', 'Lonavala', 'Regenta SGS Greenotel - Lonavala', '2 km', 2.0, 4.8, 1800, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-19', 'Khandala', 'Della Resorts', '3 km', 3.0, 4.3, 2400, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-20', 'Khandala', 'Radisson Resort & Spa Lonavala', '5 km', 5.0, 4.4, 3200, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-21', 'Lohagad Fort', 'The Chavni', '2 km', 2.0, 4.5, 4500, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-22', 'Lohagad Fort', 'The Voyage Zen Oasis', '4 km', 4.0, 4.6, 5800, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-23', 'Panshet Dam', 'MTDC Resort Panshet', '0.7 km', 0.7, 4.7, 2800, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-24', 'Panshet Dam', 'The Hosteller Panshet Lakeview', '3.0 km', 3.0, 4.8, 3500, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-25', 'Visapur Fort', 'The Chavni', '1.1 km', 1.1, 4.3, 1200, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-26', 'Visapur Fort', 'The Voyage Zen Oasis', '3.2 km', 3.2, 4.4, 1800, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-27', 'Rajmachi Fort', 'Trek Rajmachi', '0.6 km', 0.6, 4.5, 2400, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-28', 'Rajmachi Fort', 'Upper Deck Resort', '5.1 km', 5.1, 4.6, 3200, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-29', 'Rajiv Gandhi Zoological Park', 'Hotel Utsav Deluxe', '4.0 km', 4.0, 4.7, 4500, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-30', 'Rajiv Gandhi Zoological Park', 'Deccan Pavilion Katraj', '5.7 km', 5.7, 4.8, 5800, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-31', 'ISKCON NVCC, Katraj', 'Hotel HMR Royal Inn', '4 km', 4.0, 4.3, 2800, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-32', 'ISKCON NVCC, Katraj', 'Hotel Nirmal''s Executive', '5 km', 5.0, 4.4, 3500, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-33', 'Swaminarayan Temple, Narhe', 'OYO Hotel Aarambh', '0.5 km', 0.5, 4.5, 1200, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-34', 'Swaminarayan Temple, Narhe', 'Wow Executive Lodging & Boarding', '3 km', 3.0, 4.6, 1800, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-35', 'Parvati Hill', 'Hotel Utsav Deluxe', '2.0 km', 2.0, 4.7, 2400, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-36', 'Parvati Hill', 'Gandharv Residency', '2.3 km', 2.3, 4.8, 3200, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-37', 'Alandi', 'Akshay Lodge', '0.5 km', 0.5, 4.3, 4500, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-38', 'Alandi', 'OYO Ashoka Hotel Lodge Marriage Hall', '1 km', 1.0, 4.4, 5800, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-39', 'Dehu', 'Local hotels/lodges near Dehu Temple', '3 km', 3.0, 4.5, 2800, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-40', 'Dehu', 'Hotels near Dehu Road', '6 km', 6.0, 4.6, 3500, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-41', 'Phoenix Mall of the Millennium', 'The Orchid Hotel Pune', '8 km', 8.0, 4.7, 1200, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-42', 'Phoenix Mall of the Millennium', 'Radisson Blu Pune Hinjawadi', '7 km', 7.0, 4.8, 1800, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-43', 'Phoenix Marketcity Pune', 'Four Points by Sheraton Hotel & Serviced Apartments Pune', '2 km', 2.0, 4.3, 2400, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-44', 'Phoenix Marketcity Pune', 'HHI (Hotel Hindusthan International) Pune', '2 km', 2.0, 4.4, 3200, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-45', 'Amanora Mall', 'Amanora The Fern Pune Series by Marriott', '0.2 km', 0.2, 4.5, 4500, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-46', 'Amanora Mall', 'Itsy Hotels Anand Executive', '0.3 km', 0.3, 4.6, 5800, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-47', 'Seasons Mall', 'Cocoon Hotel', '1.1 km', 1.1, 4.7, 2800, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-48', 'Seasons Mall', 'Monarch Guestline Magarpatta', '0.8 km', 0.8, 4.8, 3500, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-49', 'Imagicaa', 'Novotel Imagicaa Khopoli', '0.2 km', 0.2, 4.3, 1200, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-50', 'Imagicaa', 'Radisson Resort & Spa Khopoli', '0.3 km', 0.3, 4.4, 1800, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-51', 'Pashan Lake', 'OYO 7673 The Ark Apartment Hotel', '0.9 km', 0.9, 4.5, 2400, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO hotels (id, tourism_spot, hotel_name, distance_from_spot, distance_km, rating, price_per_night, image_url) VALUES ('hotel-52', 'Pashan Lake', 'Hamlet by Daily Stays', '2.3 km', 2.3, 4.6, 3200, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80') ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-1', 'Shaniwar Wada', 'Sudamache Pohe', '0.1 km', 0.1, 'Authentic Maharashtrian & Thali', 250, 4.2, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-2', 'Shaniwar Wada', 'Hotel Aatithya', '0.7 km', 0.7, 'North Indian & Mughlai', 400, 4.3, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-3', 'Shaniwar Wada', 'Shahji''s Parantha House', '0.8 km', 0.8, 'Street Food & Snacks', 600, 4.4, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-4', 'Shaniwar Wada', 'Mohan Ice Cream', '1.0 km', 1.0, 'Cafe & Beverages', 350, 4.5, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-5', 'Shaniwar Wada', 'Maratha Samrat', '1.8 km', 1.8, 'Pure Veg Regional Delights', 800, 4.6, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-6', 'Sinhagad Fort', 'Hotel Sagara Prime', '3.8 km', 3.8, 'Multi-Cuisine & Biryani', 500, 4.7, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-7', 'Sinhagad Fort', 'Hotel Swagat Family Restaurant', '4.0 km', 4.0, 'Authentic Maharashtrian & Thali', 300, 4.8, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-8', 'Sinhagad Fort', 'Local Sinhagad food stalls', '3 km', 3.0, 'North Indian & Mughlai', 750, 4.2, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-9', 'Dagdusheth Halwai Ganpati', 'Shahji''s Parantha House', '0.6 km', 0.6, 'Street Food & Snacks', 250, 4.3, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-10', 'Dagdusheth Halwai Ganpati', 'Shreeji Ice Cream', '0.6 km', 0.6, 'Cafe & Beverages', 400, 4.4, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-11', 'Dagdusheth Halwai Ganpati', 'Hotel Pyasa Restaurant', '0.3 km', 0.3, 'Pure Veg Regional Delights', 600, 4.5, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-12', 'Dagdusheth Halwai Ganpati', 'Cafe GoodLuck', '1.5 km', 1.5, 'Multi-Cuisine & Biryani', 350, 4.6, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-13', 'Dagdusheth Halwai Ganpati', 'Moreshwar Foodee Corner', '0.6 km', 0.6, 'Authentic Maharashtrian & Thali', 800, 4.7, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-14', 'Aga Khan Palace', 'Barbeque Nation - Kalyani Nagar - Pune', '0.5 km', 0.5, 'North Indian & Mughlai', 500, 4.8, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-15', 'Aga Khan Palace', 'Saffron Restaurant - North Indian Restaurant in Pune', '1.0 km', 1.0, 'Street Food & Snacks', 300, 4.2, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-16', 'Aga Khan Palace', 'Her Highness Restaurant', '1.5 km', 1.5, 'Cafe & Beverages', 750, 4.3, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-17', 'Khadakwasla Dam', 'Hotel Mejwani Pure Veg', '1.2 km', 1.2, 'Pure Veg Regional Delights', 250, 4.4, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-18', 'Khadakwasla Dam', 'Crostarizza', '1.3 km', 1.3, 'Multi-Cuisine & Biryani', 400, 4.5, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-19', 'Khadakwasla Dam', 'Mircho Misal', '1.5 km', 1.5, 'Authentic Maharashtrian & Thali', 600, 4.6, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-20', 'Khadakwasla Dam', 'GrillKarlo', '1.6 km', 1.6, 'North Indian & Mughlai', 350, 4.7, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-21', 'Rajgad Fort', 'Rajgad Valley Restaurant', '5 km', 5.0, 'Street Food & Snacks', 800, 4.8, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-22', 'Rajgad Fort', 'Rajgad Resort Restaurant', '6 km', 6.0, 'Cafe & Beverages', 500, 4.2, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-23', 'Torna Fort', 'Torna Valley Restaurant', '4 km', 4.0, 'Pure Veg Regional Delights', 300, 4.3, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-24', 'Torna Fort', 'Local village restaurants', '5 km', 5.0, 'Multi-Cuisine & Biryani', 750, 4.4, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-25', 'Mulshi Dam', 'Basho''s Resort & Restaurant', '5.6 km', 5.6, 'Authentic Maharashtrian & Thali', 250, 4.5, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-26', 'Mulshi Dam', 'Quick Bite', '7.6 km', 7.6, 'North Indian & Mughlai', 400, 4.6, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-27', 'Mulshi Dam', 'Tikona Picnic', '8.5 km', 8.5, 'Street Food & Snacks', 600, 4.7, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-28', 'Mulshi Dam', 'Dining Cliff Cafe', '8.7 km', 8.7, 'Cafe & Beverages', 350, 4.8, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-29', 'Lonavala', 'Lonavala Local Delights', '3 km', 3.0, 'Pure Veg Regional Delights', 800, 4.2, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-30', 'Lonavala', 'Della Villa Bistro', '6 km', 6.0, 'Multi-Cuisine & Biryani', 500, 4.3, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-31', 'Lonavala', 'Mapro Garden Restaurant', '7 km', 7.0, 'Authentic Maharashtrian & Thali', 300, 4.4, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-32', 'Khandala', 'Della Villa Bistro', '2 km', 2.0, 'North Indian & Mughlai', 750, 4.5, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-33', 'Khandala', 'The Sattva', '5 km', 5.0, 'Street Food & Snacks', 250, 4.6, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-34', 'Lohagad Fort', 'The Chavni', '2 km', 2.0, 'Cafe & Beverages', 400, 4.7, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-35', 'Lohagad Fort', 'Lohagad Wadi local restaurants', '3 km', 3.0, 'Pure Veg Regional Delights', 600, 4.8, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-36', 'Panshet Dam', 'MTDC Panshet Restaurant', '1 km', 1.0, 'Multi-Cuisine & Biryani', 350, 4.2, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-37', 'Panshet Dam', 'Panshet Lake View Restaurant', '3 km', 3.0, 'Authentic Maharashtrian & Thali', 800, 4.3, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-38', 'Visapur Fort', 'The Chavni', '2 km', 2.0, 'North Indian & Mughlai', 500, 4.4, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-39', 'Visapur Fort', 'Malavli local restaurants', '4 km', 4.0, 'Street Food & Snacks', 300, 4.5, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-40', 'Rajmachi Fort', 'Rajmachi local food stalls', '1 km', 1.0, 'Cafe & Beverages', 750, 4.6, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-41', 'Rajmachi Fort', 'Udhewadi Village Restaurants', '2 km', 2.0, 'Pure Veg Regional Delights', 250, 4.7, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-42', 'Rajiv Gandhi Zoological Park', 'Hotel Utsav Deluxe', '4 km', 4.0, 'Multi-Cuisine & Biryani', 400, 4.8, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-43', 'Rajiv Gandhi Zoological Park', 'Deccan Pavilion', '5 km', 5.0, 'Authentic Maharashtrian & Thali', 600, 4.2, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-44', 'ISKCON NVCC, Katraj', 'Govinda''s -International Chain Of Restaurant', '0.1 km', 0.1, 'North Indian & Mughlai', 350, 4.3, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-45', 'ISKCON NVCC, Katraj', 'Krushnasagar Pure Veg Restaurant', '3 km', 3.0, 'Street Food & Snacks', 800, 4.4, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-46', 'Swaminarayan Temple, Narhe', 'Narayan dining', '0.5 km', 0.5, 'Cafe & Beverages', 500, 4.5, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-47', 'Swaminarayan Temple, Narhe', 'Shreeji Pure Veg - Narhe', '2 km', 2.0, 'Pure Veg Regional Delights', 300, 4.6, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-48', 'Parvati Hill', 'The Sky Kitchen & Banquets', '2.3 km', 2.3, 'Multi-Cuisine & Biryani', 750, 4.7, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-49', 'Parvati Hill', 'Cafe Peter', '1.8 km', 1.8, 'Authentic Maharashtrian & Thali', 250, 4.8, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-50', 'Parvati Hill', 'La Casetta', '2.2 km', 2.2, 'North Indian & Mughlai', 400, 4.2, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-51', 'Parvati Hill', 'Jolly Jars', '1.2 km', 1.2, 'Street Food & Snacks', 600, 4.3, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-52', 'Alandi', 'Local restaurants near Alandi Temple', '1 km', 1.0, 'Cafe & Beverages', 350, 4.4, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-53', 'Alandi', 'Prasad restaurants near temple', '1 km', 1.0, 'Pure Veg Regional Delights', 800, 4.5, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-54', 'Dehu', 'Restaurants near Dehu Gatha Temple', '1 km', 1.0, 'Multi-Cuisine & Biryani', 500, 4.6, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-55', 'Dehu', 'Local Maharashtrian restaurants', '2 km', 2.0, 'Authentic Maharashtrian & Thali', 300, 4.7, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-56', 'Phoenix Mall of the Millennium', 'Restaurants inside Phoenix Mall', '0.2 km', 0.2, 'North Indian & Mughlai', 750, 4.8, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-57', 'Phoenix Mall of the Millennium', 'Food court', '0.2 km', 0.2, 'Street Food & Snacks', 250, 4.2, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-58', 'Phoenix Marketcity Pune', 'Copper Chimney Viman Nagar', '0.5 km', 0.5, 'Cafe & Beverages', 400, 4.3, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-59', 'Phoenix Marketcity Pune', 'Restaurants inside Phoenix Marketcity', '0.2 km', 0.2, 'Pure Veg Regional Delights', 600, 4.4, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-60', 'Amanora Mall', 'Hard Rock Cafe', '0 km', 0.0, 'Multi-Cuisine & Biryani', 350, 4.5, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-61', 'Amanora Mall', 'Wah Marathi', '0.3 km', 0.3, 'Authentic Maharashtrian & Thali', 800, 4.6, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-62', 'Amanora Mall', 'Burger King', '0.2 km', 0.2, 'North Indian & Mughlai', 500, 4.7, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-63', 'Amanora Mall', 'Indimex', '0.3 km', 0.3, 'Street Food & Snacks', 300, 4.8, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-64', 'Seasons Mall', 'Shanghai Spice & Sizzlers', '0 km', 0.0, 'Cafe & Beverages', 750, 4.2, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-65', 'Seasons Mall', 'Wah Marathi', '0.1 km', 0.1, 'Pure Veg Regional Delights', 250, 4.3, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-66', 'Seasons Mall', 'Hard Rock Cafe', '0.3 km', 0.3, 'Multi-Cuisine & Biryani', 400, 4.4, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-67', 'Seasons Mall', 'Cafe Arabia', '0.1 km', 0.1, 'Authentic Maharashtrian & Thali', 600, 4.5, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-68', 'Imagicaa', 'Novotel Imagicaa Restaurant', '0.2 km', 0.2, 'North Indian & Mughlai', 350, 4.6, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-69', 'Imagicaa', 'Imagicaa Food Court', '0.2 km', 0.2, 'Street Food & Snacks', 800, 4.7, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-70', 'Lal Mahal', 'Restaurants near Shaniwar Wada', '1 km', 1.0, 'Cafe & Beverages', 500, 4.8, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-71', 'Lal Mahal', 'Sudamache Pohe', '1 km', 1.0, 'Pure Veg Regional Delights', 300, 4.2, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-72', 'Pashan Lake', 'Restaurants near Pashan-Sus Road', '1 km', 1.0, 'Multi-Cuisine & Biryani', 750, 4.3, FALSE) ON CONFLICT (id) DO NOTHING;
INSERT INTO restaurants (id, tourism_spot, restaurant_name, distance_from_spot, distance_km, cuisine, price_for_two, rating, is_pure_veg) VALUES ('rest-73', 'Pashan Lake', 'Café/restaurant options near Baner', '3 km', 3.0, 'Authentic Maharashtrian & Thali', 250, 4.4, TRUE) ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-1', 'Shaniwar Wada', 'Pune Heritage Guide', '₹500', 500, 4.6, 'Heritage & Historical Lore') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-2', 'Shaniwar Wada', 'Maratha History Guide', '₹700', 700, 4.7, 'Heritage & Historical Lore') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-3', 'Sinhagad Fort', 'Sinhagad Local Trek Guide', '₹700', 700, 4.8, 'Trek & Adventure') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-4', 'Sinhagad Fort', 'Sahyadri Trek Guide', '₹1', 1, 4.9, 'Trek & Adventure') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-5', 'Dagdusheth Halwai Ganpati', 'Pune Temple Guide', '₹400', 400, 4.6, 'Culture & Local Tourism') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-6', 'Dagdusheth Halwai Ganpati', 'Pune Heritage Guide', '₹600', 600, 4.7, 'Heritage & Historical Lore') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-7', 'Aga Khan Palace', 'Gandhi History Guide', '₹500', 500, 4.8, 'Heritage & Historical Lore') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-8', 'Aga Khan Palace', 'Pune Heritage Guide', '₹700', 700, 4.9, 'Heritage & Historical Lore') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-9', 'Khadakwasla Dam', 'Pune Nature Guide', '₹500', 500, 4.6, 'Culture & Local Tourism') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-10', 'Khadakwasla Dam', 'Local Sightseeing Guide', '₹700', 700, 4.7, 'Culture & Local Tourism') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-11', 'Rajgad Fort', 'Rajgad Trek Guide', '₹1', 1, 4.8, 'Trek & Adventure') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-12', 'Rajgad Fort', 'Sahyadri Adventure Guide', '₹1', 1, 4.9, 'Culture & Local Tourism') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-13', 'Torna Fort', 'Torna Trek Guide', '₹1', 1, 4.6, 'Trek & Adventure') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-14', 'Torna Fort', 'Sahyadri Local Guide', '₹1', 1, 4.7, 'Culture & Local Tourism') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-15', 'Mulshi Dam', 'Mulshi Nature Guide', '₹700', 700, 4.8, 'Culture & Local Tourism') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-16', 'Mulshi Dam', 'Adventure & Nature Guide', '₹1', 1, 4.9, 'Culture & Local Tourism') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-17', 'Lonavala', 'Lonavala Sightseeing Guide', '₹700', 700, 4.6, 'Culture & Local Tourism') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-18', 'Lonavala', 'Adventure Tour Guide', '₹1', 1, 4.7, 'Culture & Local Tourism') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-19', 'Khandala', 'Khandala Local Guide', '₹600', 600, 4.8, 'Culture & Local Tourism') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-20', 'Khandala', 'Hill Station Guide', '₹800', 800, 4.9, 'Culture & Local Tourism') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-21', 'Lohagad Fort', 'Lohagad Trek Guide', '₹700', 700, 4.6, 'Trek & Adventure') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-22', 'Lohagad Fort', 'Fort History Guide', '₹1', 1, 4.7, 'Heritage & Historical Lore') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-23', 'Panshet Dam', 'Panshet Local Guide', '₹600', 600, 4.8, 'Culture & Local Tourism') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-24', 'Panshet Dam', 'Water Adventure Guide', '₹900', 900, 4.9, 'Culture & Local Tourism') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-25', 'Visapur Fort', 'Visapur Trek Guide', '₹700', 700, 4.6, 'Trek & Adventure') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-26', 'Visapur Fort', 'Sahyadri Trek Guide', '₹1', 1, 4.7, 'Trek & Adventure') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-27', 'Rajmachi Fort', 'Rajmachi Trek Guide', '₹1', 1, 4.8, 'Trek & Adventure') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-28', 'Rajmachi Fort', 'Adventure Trek Guide', '₹1', 1, 4.9, 'Trek & Adventure') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-29', 'Rajiv Gandhi Zoological Park', 'Wildlife Guide', '₹500', 500, 4.6, 'Culture & Local Tourism') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-30', 'Rajiv Gandhi Zoological Park', 'Nature & Wildlife Guide', '₹700', 700, 4.7, 'Culture & Local Tourism') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-31', 'ISKCON NVCC, Katraj', 'Spiritual Guide', '₹400', 400, 4.8, 'Culture & Local Tourism') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-32', 'ISKCON NVCC, Katraj', 'Temple & Culture Guide', '₹600', 600, 4.9, 'Culture & Local Tourism') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-33', 'Swaminarayan Temple, Narhe', 'Temple Guide', '₹400', 400, 4.6, 'Culture & Local Tourism') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-34', 'Swaminarayan Temple, Narhe', 'Spiritual & Architecture Guide', '₹600', 600, 4.7, 'Culture & Local Tourism') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-35', 'Parvati Hill Temple', 'Pune Heritage Guide', '₹500', 500, 4.8, 'Heritage & Historical Lore') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-36', 'Parvati Hill Temple', 'Temple & History Guide', '₹700', 700, 4.9, 'Heritage & Historical Lore') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-37', 'Alandi', 'Pilgrimage Guide', '₹500', 500, 4.6, 'Culture & Local Tourism') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-38', 'Alandi', 'Dnyaneshwar Maharaj Heritage Guide', '₹700', 700, 4.7, 'Heritage & Historical Lore') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-39', 'Dehu', 'Pilgrimage Guide', '₹500', 500, 4.8, 'Culture & Local Tourism') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-40', 'Dehu', 'Sant Tukaram Heritage Guide', '₹700', 700, 4.9, 'Heritage & Historical Lore') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-41', 'Phoenix Mall of the Millennium', 'Shopping Guide', '₹300', 300, 4.6, 'Culture & Local Tourism') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-42', 'Phoenix Mall of the Millennium', 'Entertainment Guide', '₹500', 500, 4.7, 'Culture & Local Tourism') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-43', 'Imagicaa', 'Theme Park Guide', '₹500', 500, 4.8, 'Culture & Local Tourism') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-44', 'Imagicaa', 'Adventure & Family Guide', '₹800', 800, 4.9, 'Culture & Local Tourism') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-45', 'Lal Mahal', 'Maratha History Guide', '₹400', 400, 4.6, 'Heritage & Historical Lore') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-46', 'Lal Mahal', 'Heritage Guide', '₹600', 600, 4.7, 'Heritage & Historical Lore') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-47', 'Pashan Lake', 'Nature & Birdwatching Guide', '₹500', 500, 4.8, 'Culture & Local Tourism') ON CONFLICT (id) DO NOTHING;
INSERT INTO guides (id, tourism_spot, guide_name, approx_guide_price, price_inr, rating, specialization) VALUES ('guide-48', 'Pashan Lake', 'Photography & Nature Guide', '₹700', 700, 4.9, 'Culture & Local Tourism') ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-1', 'Shaniwar Wada', 'Seven Wonders Dream Park', 3.0, 'Theme Park & Rides', 50, 4.4) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-2', 'Shaniwar Wada', 'The Pavillion', 2.9, 'Shopping & Mall', 100, 4.5) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-3', 'Sinhagad Fort', 'Khadakwasla Dam', 12.0, 'Nature & Viewpoint', 200, 4.6) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-4', 'Sinhagad Fort', 'Fun Time Multiplex', 20.0, 'Sightseeing & Leisure', 350, 4.7) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-5', 'Dagdusheth Halwai Ganpati', 'Laxmi Road', 0.8, 'Sightseeing & Leisure', 0, 4.8) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-6', 'Dagdusheth Halwai Ganpati', 'Darshan Museum', 2.3, 'Sightseeing & Leisure', 150, 4.4) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-7', 'Aga Khan Palace', 'Phoenix Marketcity Pune', 2.5, 'Sightseeing & Leisure', 500, 4.5) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-8', 'Aga Khan Palace', 'Osho Teerth Park', 2.5, 'Theme Park & Rides', 750, 4.6) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-9', 'Khadakwasla Dam', 'Sinhagad Fort', 12.0, 'Sightseeing & Leisure', 50, 4.7) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-10', 'Khadakwasla Dam', 'Fun Time Multiplex', 9.0, 'Sightseeing & Leisure', 100, 4.8) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-11', 'Rajgad Fort', 'Gunjavane Dam', 8.0, 'Nature & Viewpoint', 200, 4.4) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-12', 'Rajgad Fort', 'Torna Fort', 12.0, 'Sightseeing & Leisure', 350, 4.5) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-13', 'Torna Fort', 'Gunjavane Dam', 2.9, 'Nature & Viewpoint', 0, 4.6) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-14', 'Torna Fort', 'Rajgad Fort', 12.1, 'Sightseeing & Leisure', 150, 4.7) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-15', 'Mulshi Dam', 'Mulshi Backwaters Viewpoint', 2.0, 'Nature & Viewpoint', 500, 4.8) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-16', 'Mulshi Dam', 'Tamhini Ghat', 20.0, 'Sightseeing & Leisure', 750, 4.4) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-17', 'Lonavala', 'Della Adventure Park', 6.0, 'Theme Park & Rides', 50, 4.5) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-18', 'Lonavala', 'Imagicaa Theme Park', 25.0, 'Theme Park & Rides', 100, 4.6) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-19', 'Khandala', 'Khandala Ghat View Point', 0.5, 'Nature & Viewpoint', 200, 4.7) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-20', 'Khandala', 'Della Adventure Park', 4.0, 'Theme Park & Rides', 350, 4.8) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-21', 'Lohagad Fort', 'Visapur Fort', 1.2, 'Sightseeing & Leisure', 0, 4.4) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-22', 'Lohagad Fort', 'Bhaja Caves', 2.4, 'Sightseeing & Leisure', 150, 4.5) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-23', 'Panshet Dam', 'Panshet Boating', 1.0, 'Sightseeing & Leisure', 500, 4.6) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-24', 'Panshet Dam', 'Krishnai Water Park', 6.4, 'Theme Park & Rides', 750, 4.7) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-25', 'Visapur Fort', 'Lohagad Fort', 1.2, 'Sightseeing & Leisure', 50, 4.8) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-26', 'Visapur Fort', 'Bhaja Caves', 2.5, 'Sightseeing & Leisure', 100, 4.4) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-27', 'Rajmachi Fort', 'Rajmachi Point', 5.0, 'Nature & Viewpoint', 200, 4.5) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-28', 'Rajmachi Fort', 'Lonavala Lake', 12.0, 'Sightseeing & Leisure', 350, 4.6) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-29', 'Rajiv Gandhi Zoological Park', 'Pune Snake Park', 0.0, 'Theme Park & Rides', 0, 4.7) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-30', 'Rajiv Gandhi Zoological Park', 'Seven Wonders Dream Park', 5.0, 'Theme Park & Rides', 150, 4.8) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-31', 'ISKCON NVCC, Katraj', 'Pune Snake Park', 3.0, 'Theme Park & Rides', 500, 4.4) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-32', 'ISKCON NVCC, Katraj', 'Flying Panda Theme Park', 4.0, 'Theme Park & Rides', 750, 4.5) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-33', 'Swaminarayan Temple, Narhe', 'Butterfly Trampoline Park', 3.0, 'Theme Park & Rides', 50, 4.6) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-34', 'Swaminarayan Temple, Narhe', 'Fun Time Multiplex', 4.0, 'Sightseeing & Leisure', 100, 4.7) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-35', 'Parvati Hill', 'Seven Wonders Dream Park', 2.0, 'Theme Park & Rides', 200, 4.8) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-36', 'Parvati Hill', 'Sarasbaug', 2.0, 'Sightseeing & Leisure', 350, 4.4) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-37', 'Alandi', 'Nova Fun Zone & Trampoline Park', 3.0, 'Theme Park & Rides', 0, 4.5) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-38', 'Alandi', 'Appu Ghar, Nigdi', 12.0, 'Sightseeing & Leisure', 150, 4.6) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-39', 'Dehu', 'Appu Ghar, Nigdi', 8.0, 'Sightseeing & Leisure', 500, 4.7) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-40', 'Dehu', 'Bird Valley Udyan, Chinchwad', 10.0, 'Sightseeing & Leisure', 750, 4.8) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-41', 'Phoenix Mall of the Millennium', 'Indoor Gaming Zone', 0.0, 'Sightseeing & Leisure', 50, 4.4) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-42', 'Phoenix Mall of the Millennium', 'Cinema / Multiplex', 0.0, 'Sightseeing & Leisure', 100, 4.5) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-43', 'Imagicaa', 'Imagicaa Theme Park', 0.0, 'Theme Park & Rides', 200, 4.6) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-44', 'Imagicaa', 'Imagicaa Water Park', 0.0, 'Theme Park & Rides', 350, 4.7) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-45', 'Lal Mahal', 'Shaniwar Wada', 0.5, 'Sightseeing & Leisure', 0, 4.8) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-46', 'Lal Mahal', 'Laxmi Road Shopping Area', 0.8, 'Sightseeing & Leisure', 150, 4.4) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-47', 'Pashan Lake', 'Gram Sanskruti Udyan', 4.0, 'Sightseeing & Leisure', 500, 4.5) ON CONFLICT (id) DO NOTHING;
INSERT INTO entertainments (id, tourism_spot, entertainment_place, distance_from_spot_km, category, approx_entry_fee, rating) VALUES ('ent-48', 'Pashan Lake', 'The Pavillion Mall', 4.0, 'Shopping & Mall', 750, 4.6) ON CONFLICT (id) DO NOTHING;
INSERT INTO taxi_routes (id, tourism_spot, distance_from_pune, distance_km, approx_taxi_fare, fare_amount, best_travel_option) VALUES ('taxi-1', 'Shaniwar Wada', '3 km', 3.0, '₹300', 300, 'GreenRide Zero-Emission EV Cab (Direct from Pune Hub to Shaniwar Wada)') ON CONFLICT (id) DO NOTHING;
INSERT INTO taxi_routes (id, tourism_spot, distance_from_pune, distance_km, approx_taxi_fare, fare_amount, best_travel_option) VALUES ('taxi-2', 'Sinhagad Fort', '30 km', 30.0, '₹690', 690, 'GreenRide Zero-Emission EV Cab (Direct from Pune Hub to Sinhagad Fort)') ON CONFLICT (id) DO NOTHING;
INSERT INTO taxi_routes (id, tourism_spot, distance_from_pune, distance_km, approx_taxi_fare, fare_amount, best_travel_option) VALUES ('taxi-3', 'Dagdusheth Halwai Ganpati', '3 km', 3.0, '₹300', 300, 'GreenRide Zero-Emission EV Cab (Direct from Pune Hub to Dagdusheth Halwai Ganpati)') ON CONFLICT (id) DO NOTHING;
INSERT INTO taxi_routes (id, tourism_spot, distance_from_pune, distance_km, approx_taxi_fare, fare_amount, best_travel_option) VALUES ('taxi-4', 'Aga Khan Palace', '6 km', 6.0, '₹300', 300, 'GreenRide Zero-Emission EV Cab (Direct from Pune Hub to Aga Khan Palace)') ON CONFLICT (id) DO NOTHING;
INSERT INTO taxi_routes (id, tourism_spot, distance_from_pune, distance_km, approx_taxi_fare, fare_amount, best_travel_option) VALUES ('taxi-5', 'Khadakwasla Dam', '20 km', 20.0, '₹510', 510, 'GreenRide Zero-Emission EV Cab (Direct from Pune Hub to Khadakwasla Dam)') ON CONFLICT (id) DO NOTHING;
INSERT INTO taxi_routes (id, tourism_spot, distance_from_pune, distance_km, approx_taxi_fare, fare_amount, best_travel_option) VALUES ('taxi-6', 'Rajgad Fort', '60 km', 60.0, '₹1230', 1230, 'GreenRide Zero-Emission EV Cab (Direct from Pune Hub to Rajgad Fort)') ON CONFLICT (id) DO NOTHING;
INSERT INTO taxi_routes (id, tourism_spot, distance_from_pune, distance_km, approx_taxi_fare, fare_amount, best_travel_option) VALUES ('taxi-7', 'Torna Fort', '65 km', 65.0, '₹1320', 1320, 'GreenRide Zero-Emission EV Cab (Direct from Pune Hub to Torna Fort)') ON CONFLICT (id) DO NOTHING;
INSERT INTO taxi_routes (id, tourism_spot, distance_from_pune, distance_km, approx_taxi_fare, fare_amount, best_travel_option) VALUES ('taxi-8', 'Mulshi Dam', '45 km', 45.0, '₹960', 960, 'GreenRide Zero-Emission EV Cab (Direct from Pune Hub to Mulshi Dam)') ON CONFLICT (id) DO NOTHING;
INSERT INTO taxi_routes (id, tourism_spot, distance_from_pune, distance_km, approx_taxi_fare, fare_amount, best_travel_option) VALUES ('taxi-9', 'Lonavala', '65 km', 65.0, '₹1320', 1320, 'GreenRide Zero-Emission EV Cab (Direct from Pune Hub to Lonavala)') ON CONFLICT (id) DO NOTHING;
INSERT INTO taxi_routes (id, tourism_spot, distance_from_pune, distance_km, approx_taxi_fare, fare_amount, best_travel_option) VALUES ('taxi-10', 'Khandala', '70 km', 70.0, '₹1410', 1410, 'GreenRide Zero-Emission EV Cab (Direct from Pune Hub to Khandala)') ON CONFLICT (id) DO NOTHING;
INSERT INTO taxi_routes (id, tourism_spot, distance_from_pune, distance_km, approx_taxi_fare, fare_amount, best_travel_option) VALUES ('taxi-11', 'Lohagad Fort', '65 km', 65.0, '₹1320', 1320, 'GreenRide Zero-Emission EV Cab (Direct from Pune Hub to Lohagad Fort)') ON CONFLICT (id) DO NOTHING;
INSERT INTO taxi_routes (id, tourism_spot, distance_from_pune, distance_km, approx_taxi_fare, fare_amount, best_travel_option) VALUES ('taxi-12', 'Panshet Dam', '50 km', 50.0, '₹1050', 1050, 'GreenRide Zero-Emission EV Cab (Direct from Pune Hub to Panshet Dam)') ON CONFLICT (id) DO NOTHING;
INSERT INTO taxi_routes (id, tourism_spot, distance_from_pune, distance_km, approx_taxi_fare, fare_amount, best_travel_option) VALUES ('taxi-13', 'Visapur Fort', '65 km', 65.0, '₹1320', 1320, 'GreenRide Zero-Emission EV Cab (Direct from Pune Hub to Visapur Fort)') ON CONFLICT (id) DO NOTHING;
INSERT INTO taxi_routes (id, tourism_spot, distance_from_pune, distance_km, approx_taxi_fare, fare_amount, best_travel_option) VALUES ('taxi-14', 'Rajmachi Fort', '80 km', 80.0, '₹1590', 1590, 'GreenRide Zero-Emission EV Cab (Direct from Pune Hub to Rajmachi Fort)') ON CONFLICT (id) DO NOTHING;
INSERT INTO taxi_routes (id, tourism_spot, distance_from_pune, distance_km, approx_taxi_fare, fare_amount, best_travel_option) VALUES ('taxi-15', 'Rajiv Gandhi Zoological Park', '8 km', 8.0, '₹300', 300, 'GreenRide Zero-Emission EV Cab (Direct from Pune Hub to Rajiv Gandhi Zoological Park)') ON CONFLICT (id) DO NOTHING;
INSERT INTO taxi_routes (id, tourism_spot, distance_from_pune, distance_km, approx_taxi_fare, fare_amount, best_travel_option) VALUES ('taxi-16', 'ISKCON NVCC, Katraj', '12 km', 12.0, '₹366', 366, 'GreenRide Zero-Emission EV Cab (Direct from Pune Hub to ISKCON NVCC, Katraj)') ON CONFLICT (id) DO NOTHING;
INSERT INTO taxi_routes (id, tourism_spot, distance_from_pune, distance_km, approx_taxi_fare, fare_amount, best_travel_option) VALUES ('taxi-17', 'Swaminarayan Temple, Narhe', '15 km', 15.0, '₹420', 420, 'GreenRide Zero-Emission EV Cab (Direct from Pune Hub to Swaminarayan Temple, Narhe)') ON CONFLICT (id) DO NOTHING;
INSERT INTO taxi_routes (id, tourism_spot, distance_from_pune, distance_km, approx_taxi_fare, fare_amount, best_travel_option) VALUES ('taxi-18', 'Parvati Hill Temple', '6 km', 6.0, '₹300', 300, 'GreenRide Zero-Emission EV Cab (Direct from Pune Hub to Parvati Hill Temple)') ON CONFLICT (id) DO NOTHING;
INSERT INTO taxi_routes (id, tourism_spot, distance_from_pune, distance_km, approx_taxi_fare, fare_amount, best_travel_option) VALUES ('taxi-19', 'Alandi', '25 km', 25.0, '₹600', 600, 'GreenRide Zero-Emission EV Cab (Direct from Pune Hub to Alandi)') ON CONFLICT (id) DO NOTHING;
INSERT INTO taxi_routes (id, tourism_spot, distance_from_pune, distance_km, approx_taxi_fare, fare_amount, best_travel_option) VALUES ('taxi-20', 'Dehu', '30 km', 30.0, '₹690', 690, 'GreenRide Zero-Emission EV Cab (Direct from Pune Hub to Dehu)') ON CONFLICT (id) DO NOTHING;
INSERT INTO taxi_routes (id, tourism_spot, distance_from_pune, distance_km, approx_taxi_fare, fare_amount, best_travel_option) VALUES ('taxi-21', 'Phoenix Mall of the Millennium', '15 km', 15.0, '₹420', 420, 'GreenRide Zero-Emission EV Cab (Direct from Pune Hub to Phoenix Mall of the Millennium)') ON CONFLICT (id) DO NOTHING;
INSERT INTO taxi_routes (id, tourism_spot, distance_from_pune, distance_km, approx_taxi_fare, fare_amount, best_travel_option) VALUES ('taxi-22', 'Phoenix Marketcity Pune', '8 km', 8.0, '₹300', 300, 'GreenRide Zero-Emission EV Cab (Direct from Pune Hub to Phoenix Marketcity Pune)') ON CONFLICT (id) DO NOTHING;
INSERT INTO taxi_routes (id, tourism_spot, distance_from_pune, distance_km, approx_taxi_fare, fare_amount, best_travel_option) VALUES ('taxi-23', 'Amanora Mall', '10 km', 10.0, '₹330', 330, 'GreenRide Zero-Emission EV Cab (Direct from Pune Hub to Amanora Mall)') ON CONFLICT (id) DO NOTHING;
INSERT INTO taxi_routes (id, tourism_spot, distance_from_pune, distance_km, approx_taxi_fare, fare_amount, best_travel_option) VALUES ('taxi-24', 'Seasons Mall', '10 km', 10.0, '₹330', 330, 'GreenRide Zero-Emission EV Cab (Direct from Pune Hub to Seasons Mall)') ON CONFLICT (id) DO NOTHING;
INSERT INTO taxi_routes (id, tourism_spot, distance_from_pune, distance_km, approx_taxi_fare, fare_amount, best_travel_option) VALUES ('taxi-25', 'Imagicaa', '90 km', 90.0, '₹1770', 1770, 'GreenRide Zero-Emission EV Cab (Direct from Pune Hub to Imagicaa)') ON CONFLICT (id) DO NOTHING;
INSERT INTO taxi_routes (id, tourism_spot, distance_from_pune, distance_km, approx_taxi_fare, fare_amount, best_travel_option) VALUES ('taxi-26', 'Lal Mahal', '3 km', 3.0, '₹300', 300, 'GreenRide Zero-Emission EV Cab (Direct from Pune Hub to Lal Mahal)') ON CONFLICT (id) DO NOTHING;
INSERT INTO taxi_routes (id, tourism_spot, distance_from_pune, distance_km, approx_taxi_fare, fare_amount, best_travel_option) VALUES ('taxi-27', 'Pashan Lake', '10 km', 10.0, '₹330', 330, 'GreenRide Zero-Emission EV Cab (Direct from Pune Hub to Pashan Lake)') ON CONFLICT (id) DO NOTHING;